name: grow-backend
channels:
  - conda-forge
dependencies:
  - python>3.10
  - fastapi
  - uvicorn
  - pydantic
  - python-dotenv

  # Databases
  - psycopg2-binary
  - sqlalchemy
  - alembic
  - asyncpg

  # Testing
  - pytest
  - pytest-asyncio
  - httpx
